### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operat ion: [torch.cuda.LongTensor [8]] is at version 3; expected version 2 instead. Hint: the backtrace further  above shows the operation that failed to compute its gradient. The variable in question was changed in t here or anywhere later. Good luck!

### ISSUE THREAD

**Issue by JerrryNie** [seanie12/SWEP#3]
Hi, when I'm training your model, it occurs:
`You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):                                                                                                                          
  File "run_squad.py", line 318, in <module>
    run(args)
  File "run_squad.py", line 244, in run
    loss.backward()
  File "/data/nyx/miniconda3/envs/swep/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data/nyx/miniconda3/envs/swep/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.LongTensor [8]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).`

And when I set `torch.autograd.set_detect_anomaly(True)`, the complete output is:
`Warning: Traceback of forward call that caused the error:
  File "run_squad.py", line 318, in <module>
    run(args)
  File "run_squad.py", line 235, in run
    outputs = model(**inputs)
  File "/data/nyx/miniconda3/envs/swep/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/nyx/qa/uqa/baselines/SWEP/models.py", line 79, in forward
    noise_outputs = self.bert_model(**inputs)
  File "/data/nyx/miniconda3/envs/swep/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/nyx/miniconda3/envs/swep/lib/python3.6/site-packages/transformers/modeling_bert.py", line 1565, in forward
    end_loss = loss_fct(end_logits, end_positions)
  File "/data/nyx/miniconda3/envs/swep/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/nyx/miniconda3/envs/swep/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/data/nyx/miniconda3/envs/swep/lib/python3.6/site-packages/torch/nn/functional.py", line 2021, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/data/nyx/miniconda3/envs/swep/lib/python3.6/site-packages/torch/nn/functional.py", line 1838, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
 (print_stack at /opt/conda/conda-bld/pytorch_1579022034529/work/torch/csrc/autograd/python_anomaly_mode.cpp:57)
Traceback (most recent call last):                                                                                                                          
  File "run_squad.py", line 318, in <module>
    run(args)
  File "run_squad.py", line 244, in run
    loss.backward()
  File "/data/nyx/miniconda3/envs/swep/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data/nyx/miniconda3/envs/swep/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.LongTensor [8]] is at version 3; expected version 2 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!`

Besides, when I replace VariationalBert with a normal BERTQA model (just training a BERTQA model), everything works well.  Therefore, something may be wrong in your implementation in VariationalBert.

So I just wonder how to fix that error. Thanks!

**Comment by JerrryNie** [comment]
I've combined the `inputs` and `news_input` and send them simultaneously to the BERT model, and then the model works well. But I just wonder if it is the exact code that you want to build your model?
The modified code is here (in models.py):
      
```
            inputs_embeds = embeddings(input_ids)
            # inputs = {"inputs_embeds": inputs_embeds * noise,
            #           "attention_mask": attention_mask,
            #           "token_type_ids": token_type_ids,
            #           "start_positions": start_positions,
            #           "end_positions": end_positions}

            # noise_outputs = self.bert_model(**inputs)
            # noise_loss = noise_outputs[0]

            # new_inputs = {"inputs_embeds": inputs_embeds,
            #               "attention_mask": attention_mask,
            #               "token_type_ids": token_type_ids,
            #               "start_positions": start_positions,
            #               "end_positions": end_positions}

            # outputs = self.bert_model(**new_inputs)
            total_inputs_embeds = torch.cat([inputs_embeds * noise, inputs_embeds], 0)
            total_attention_mask = torch.cat([attention_mask, attention_mask], 0)
            total_token_type_ids = torch.cat([token_type_ids, token_type_ids], 0)
            total_start_positions = torch.cat([start_positions, start_positions], 0)
            total_end_positions = torch.cat([end_positions, end_positions], 0)
            total_inputs = {"inputs_embeds": total_inputs_embeds,
                            "attention_mask": total_attention_mask,
                            "token_type_ids": total_token_type_ids,
                            "start_positions": total_start_positions,
                            "end_positions": total_end_positions}
            outputs = self.bert_model(**total_inputs)
            # nll = outputs[0]
            loss = outputs[0]
            # loss = 0.5 * (nll + noise_loss)
            return (loss, kl)
```

**Comment by seanie12** [comment]
Thanks.

I forgot to specify it in README. 

The error is due to the in-place operation in BERTforQuestionAnswering forward pass [here](https://github.com/huggingface/transformers/blob/master/src/transformers/models/bert/modeling_bert.py#L1845).

I change it to 

`start_positions = torch.clamp(start_positions, 0, ignored_index)`
`end_positions = torch.clamp(end_positions, 0, ignored_index)`

or alternatively, you can use deepcopy as follow:

`new_inputs = {"inputs_embeds": inputs_embeds,
                           "attention_mask": attention_mask,
                           "token_type_ids": token_type_ids,
                           "start_positions": deepcopy(start_positions),
                           "end_positions": deepcopy(end_positions)}
`
Any of them including yours are equivalent.

**Comment by JerrryNie** [comment]
Thanks a lot!
